version: '3.8'

services:
  db:
    image: postgres:14
    container_name: aula_postgres
    restart: always
    environment:
      POSTGRES_DB: aula_inteligente
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - aula_net

volumes:
  postgres_data:

networks:
  aula_net:
