"""Primera migracion

Revision ID: 3f6984d24a63
Revises: 
Create Date: 2025-07-23 12:44:25.111239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f6984d24a63'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('nivel', sa.String(), nullable=False),
    sa.Column('paralelo', sa.String(), nullable=False),
    sa.Column('turno', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_cursos_id'), 'cursos', ['id'], unique=False)
    op.create_table('docentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=False),
    sa.Column('correo', sa.String(), nullable=False),
    sa.Column('genero', sa.String(), nullable=False),
    sa.Column('contrasena', sa.String(), nullable=False),
    sa.Column('is_doc', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_index(op.f('ix_docentes_id'), 'docentes', ['id'], unique=False)
    op.create_table('estudiantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('genero', sa.String(), nullable=False),
    sa.Column('url_imagen', sa.String(), nullable=True),
    sa.Column('nombre_tutor', sa.String(), nullable=True),
    sa.Column('telefono_tutor', sa.String(), nullable=True),
    sa.Column('direccion_casa', sa.String(), nullable=True),
    sa.Column('correo', sa.String(), nullable=True),
    sa.Column('contrasena', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_index(op.f('ix_estudiantes_id'), 'estudiantes', ['id'], unique=False)
    op.create_table('gestiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anio')
    )
    op.create_index(op.f('ix_gestiones_id'), 'gestiones', ['id'], unique=False)
    op.create_table('materias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_materias_id'), 'materias', ['id'], unique=False)
    op.create_table('padres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=False),
    sa.Column('correo', sa.String(), nullable=False),
    sa.Column('genero', sa.String(), nullable=False),
    sa.Column('contrasena', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_index(op.f('ix_padres_id'), 'padres', ['id'], unique=False)
    op.create_table('tipoevaluaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_tipoevaluaciones_id'), 'tipoevaluaciones', ['id'], unique=False)
    op.create_table('curso_materia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curso_materia_id'), 'curso_materia', ['id'], unique=False)
    op.create_table('docente_materia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_docente_materia_id'), 'docente_materia', ['id'], unique=False)
    op.create_table('inscripciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('gestion_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gestion_id'], ['gestiones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inscripciones_id'), 'inscripciones', ['id'], unique=False)
    op.create_table('padre_estudiante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('padre_id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['padre_id'], ['padres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_padre_estudiante_id'), 'padre_estudiante', ['id'], unique=False)
    op.create_table('periodos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('gestion_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['gestion_id'], ['gestiones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', 'gestion_id', name='uq_nombre_gestion')
    )
    op.create_index(op.f('ix_periodos_id'), 'periodos', ['id'], unique=False)
    op.create_table('peso_tipo_evaluacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('porcentaje', sa.Float(), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('gestion_id', sa.Integer(), nullable=False),
    sa.Column('tipo_evaluacion_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gestion_id'], ['gestiones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tipo_evaluacion_id'], ['tipoevaluaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peso_tipo_evaluacion_id'), 'peso_tipo_evaluacion', ['id'], unique=False)
    op.create_table('evaluaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('tipo_evaluacion_id', sa.Integer(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tipo_evaluacion_id'], ['tipoevaluaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluaciones_id'), 'evaluaciones', ['id'], unique=False)
    op.create_table('prediccion_rendimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promedio_notas', sa.Float(), nullable=False),
    sa.Column('porcentaje_asistencia', sa.Float(), nullable=False),
    sa.Column('promedio_participacion', sa.Float(), nullable=False),
    sa.Column('resultado_numerico', sa.Float(), nullable=False),
    sa.Column('clasificacion', sa.String(), nullable=False),
    sa.Column('fecha_generada', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediccion_rendimiento_id'), 'prediccion_rendimiento', ['id'], unique=False)
    op.create_table('rendimiento_final',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nota_final', sa.Float(), nullable=False),
    sa.Column('fecha_calculo', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rendimiento_final_id'), 'rendimiento_final', ['id'], unique=False)
    op.create_table('sesiones_asistencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('docente_id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('duracion_minutos', sa.Integer(), nullable=True),
    sa.Column('latitud_docente', sa.Float(), nullable=False),
    sa.Column('longitud_docente', sa.Float(), nullable=False),
    sa.Column('direccion_referencia', sa.String(length=500), nullable=True),
    sa.Column('radio_permitido_metros', sa.Integer(), nullable=True),
    sa.Column('permite_asistencia_tardia', sa.Boolean(), nullable=True),
    sa.Column('minutos_tolerancia', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sesiones_asistencia_id'), 'sesiones_asistencia', ['id'], unique=False)
    op.create_table('asistencias_estudiantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sesion_id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('presente', sa.Boolean(), nullable=True),
    sa.Column('fecha_marcado', sa.DateTime(), nullable=True),
    sa.Column('latitud_estudiante', sa.Float(), nullable=True),
    sa.Column('longitud_estudiante', sa.Float(), nullable=True),
    sa.Column('distancia_metros', sa.Float(), nullable=True),
    sa.Column('metodo_marcado', sa.String(length=20), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('es_tardanza', sa.Boolean(), nullable=True),
    sa.Column('justificado', sa.Boolean(), nullable=True),
    sa.Column('motivo_justificacion', sa.String(length=500), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesiones_asistencia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asistencias_estudiantes_id'), 'asistencias_estudiantes', ['id'], unique=False)
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=True),
    sa.Column('padre_id', sa.Integer(), nullable=True),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('evaluacion_id', sa.Integer(), nullable=True),
    sa.Column('para_estudiante', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ),
    sa.ForeignKeyConstraint(['evaluacion_id'], ['evaluaciones.id'], ),
    sa.ForeignKeyConstraint(['padre_id'], ['padres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificaciones_id'), 'notificaciones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notificaciones_id'), table_name='notificaciones')
    op.drop_table('notificaciones')
    op.drop_index(op.f('ix_asistencias_estudiantes_id'), table_name='asistencias_estudiantes')
    op.drop_table('asistencias_estudiantes')
    op.drop_index(op.f('ix_sesiones_asistencia_id'), table_name='sesiones_asistencia')
    op.drop_table('sesiones_asistencia')
    op.drop_index(op.f('ix_rendimiento_final_id'), table_name='rendimiento_final')
    op.drop_table('rendimiento_final')
    op.drop_index(op.f('ix_prediccion_rendimiento_id'), table_name='prediccion_rendimiento')
    op.drop_table('prediccion_rendimiento')
    op.drop_index(op.f('ix_evaluaciones_id'), table_name='evaluaciones')
    op.drop_table('evaluaciones')
    op.drop_index(op.f('ix_peso_tipo_evaluacion_id'), table_name='peso_tipo_evaluacion')
    op.drop_table('peso_tipo_evaluacion')
    op.drop_index(op.f('ix_periodos_id'), table_name='periodos')
    op.drop_table('periodos')
    op.drop_index(op.f('ix_padre_estudiante_id'), table_name='padre_estudiante')
    op.drop_table('padre_estudiante')
    op.drop_index(op.f('ix_inscripciones_id'), table_name='inscripciones')
    op.drop_table('inscripciones')
    op.drop_index(op.f('ix_docente_materia_id'), table_name='docente_materia')
    op.drop_table('docente_materia')
    op.drop_index(op.f('ix_curso_materia_id'), table_name='curso_materia')
    op.drop_table('curso_materia')
    op.drop_index(op.f('ix_tipoevaluaciones_id'), table_name='tipoevaluaciones')
    op.drop_table('tipoevaluaciones')
    op.drop_index(op.f('ix_padres_id'), table_name='padres')
    op.drop_table('padres')
    op.drop_index(op.f('ix_materias_id'), table_name='materias')
    op.drop_table('materias')
    op.drop_index(op.f('ix_gestiones_id'), table_name='gestiones')
    op.drop_table('gestiones')
    op.drop_index(op.f('ix_estudiantes_id'), table_name='estudiantes')
    op.drop_table('estudiantes')
    op.drop_index(op.f('ix_docentes_id'), table_name='docentes')
    op.drop_table('docentes')
    op.drop_index(op.f('ix_cursos_id'), table_name='cursos')
    op.drop_table('cursos')
    # ### end Alembic commands ###
