from .inscripcion import Inscripcion
from .curso_materia import CursoMateria
from .tipo_evaluacion import TipoEvaluacion
from .evaluacion import Evaluacion
from .peso_tipo_evaluacion import PesoTipoEvaluacion
from .rendimiento_final import RendimientoFinal
from .curso import Curso
from .docente_materia import DocenteMateria
from .gestion import Gestion
from .materia import Materia
from .docente import Docente
from .estudiante import Estudiante
from .periodo import Periodo
from .prediccion_rendimiento import PrediccionRendimiento
from .padre import Padre
from .padre_estudiante import PadreEstudiante
from .notificacion import Notificacion
from .sesion_asistencia import SesionAsistencia